### ISSUE TITLE
Always 0% when downloading in Android

### ISSUE THREAD

**Issue by pinkLovepurple** [DarkEnergyProcessor/NPPS#1]
This problem is only in Android( iOS untested ). In SIF-Win32, SIF will download those zip files whose information is recorded in db. But in Android, with official apk, it will NOT download after converting information into db file.

**Comment by MikuAuahDark** [comment]
This is known issue in Android and iOS when NPPS is used. The reason is because it **does not allow downloading data from same URL where the server is also hosted**. Patch might needed in **CKLBUpdate**, but I never figured out the patch.

If you see prod server, the URL of prod server is **prod.en-lovelive.klabgames.net**, but when downloading files, it will download files from **d.........cloudfront.net**.

**Comment by pinkLovepurple** [comment]
Ok I found a solution.
Just go to edit NPPS/modules/download/additional.php on line 87
`'url' => "http://your_dldomain_address/dlc/download.php?os={$os_ver}&type={$pkg_type}&id={$pkg_id}&index=$z",`

**Comment by MikuAuahDark** [comment]
That's useless if you only have 1 URL for your server. The temporary workaround is to add another aliases of your server address to /etc/hosts or using another server to host the files.
